"""Add passenger_id_number to bookings; sender/receiver_id to parcels

Revision ID: 026c0e13e706
Revises: 06d4458aaa68
Create Date: 2025-09-08 09:56:57.560064

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '026c0e13e706'
down_revision = '06d4458aaa68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) add as nullable
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_id_number', sa.String(length=30), nullable=True))

    # 2) backfill existing rows
    op.execute("""
        UPDATE bookings
        SET passenger_id_number = 'N/A'
        WHERE passenger_id_number IS NULL
    """)

    # 3) make NOT NULL
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('passenger_id_number', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('passenger_id_number')

    # ### end Alembic commands ###
