"""add vehicle_plate and driver_phone to parcels

Revision ID: 06d4458aaa68
Revises: 5bcf5a7332f0
Create Date: 2025-09-05 17:56:31.514819

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06d4458aaa68'
down_revision = '5bcf5a7332f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vehicle_plate', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('driver_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('driver_phone')
        batch_op.drop_column('vehicle_plate')

    # ### end Alembic commands ###
