"""Add sender_email and receiver_email to parcels

Revision ID: 34a0687e1c5f
Revises: 196100139227
Create Date: 2025-12-06 10:25:11.354428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34a0687e1c5f'
down_revision = '196100139227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('receiver_email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('receiver_email')
        batch_op.drop_column('sender_email')

    # ### end Alembic commands ###
