"""Add passenger details to bookings

Revision ID: 3a8d9fbb7b33
Revises: b15da46a0074
Create Date: 2025-09-03 15:17:51.432872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a8d9fbb7b33'
down_revision = 'b15da46a0074'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add columns as nullable first
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_expires_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('passenger_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('passenger_sex', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('passenger_age', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('passenger_phone', sa.String(length=20), nullable=True))
    
    # Set default values for existing records
    op.execute("""
        UPDATE bookings 
        SET 
            passenger_name = 'Passenger',
            passenger_sex = 'other',
            passenger_age = 18,
            passenger_phone = 'N/A'
        WHERE passenger_name IS NULL
    """)
    
    # Now alter columns to be NOT NULL
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('passenger_name', nullable=False)
        batch_op.alter_column('passenger_sex', nullable=False)
        batch_op.alter_column('passenger_age', nullable=False)
        batch_op.alter_column('passenger_phone', nullable=False)

    # Add ticket columns with defaults
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('issue_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
    
    # Set default values for ticket status
    op.execute("""
        UPDATE tickets 
        SET 
            issue_date = NOW(),
            status = 'valid'
        WHERE issue_date IS NULL
    """)
    
    # Make ticket status NOT NULL
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('issue_date')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('hold_expires_at')
        batch_op.drop_column('passenger_phone')
        batch_op.drop_column('passenger_age')
        batch_op.drop_column('passenger_sex')
        batch_op.drop_column('passenger_name')
    # ### end Alembic commands ###
