"""Add driver_name to parcels

Revision ID: 3ec296bdc798
Revises: 34a0687e1c5f
Create Date: 2025-12-06 10:48:41.750786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ec296bdc798'
down_revision = '34a0687e1c5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_column('driver_name')

    # ### end Alembic commands ###
