"""Add booking_seats for multi-seat bookings

Revision ID: 45284ac85253
Revises: 8949f0f9c30c
Create Date: 2026-01-15 10:12:25.291505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45284ac85253'
down_revision = '8949f0f9c30c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking_seats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=False),
    sa.Column('seat_number', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_id', 'seat_number', name='uq_trip_seat_booking')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.alter_column('seat_number',
               existing_type=sa.VARCHAR(length=5),
               nullable=True)
        batch_op.drop_constraint('uq_trip_seat', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_trip_seat', ['trip_id', 'seat_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('seat_number',
               existing_type=sa.VARCHAR(length=5),
               nullable=False)

    op.drop_table('booking_seats')
    # ### end Alembic commands ###
