"""add driver fields to trips

Revision ID: 46402d9b7ab7
Revises: 741ffd5dc998
Create Date: 2025-09-08 18:46:01.642418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46402d9b7ab7'
down_revision = '741ffd5dc998'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('driver_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('driver_phone', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('driver_phone')
        batch_op.drop_column('driver_name')

    # ### end Alembic commands ###
