"""add pickup_location to bookings

Revision ID: 741ffd5dc998
Revises: ad91a0519b72
Create Date: 2025-09-08 18:16:33.980879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741ffd5dc998'
down_revision = 'ad91a0519b72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pickup_location', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('pickup_location')

    # ### end Alembic commands ###
