"""Add guest booking support and parcel tracking key

Revision ID: 8949f0f9c30c
Revises: d2ae8adfa42a
Create Date: 2026-01-14 22:02:28.699378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8949f0f9c30c'
down_revision = 'd2ae8adfa42a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passenger_email', sa.String(length=120), nullable=False))

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tracking_key', sa.String(length=32), nullable=False))
        batch_op.create_unique_constraint(None, ['tracking_key'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('tracking_key')

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('passenger_email')

    # ### end Alembic commands ###
