"""Add is_full field to trips

Revision ID: a4c13fc277a2
Revises: 3ec296bdc798
Create Date: 2025-12-07 19:02:56.265180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4c13fc277a2'
down_revision = '3ec296bdc798'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_full', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trips', schema=None) as batch_op:
        batch_op.drop_column('is_full')

    # ### end Alembic commands ###
