"""Use origin_name and destination_name on parcels

Revision ID: b10d60b41d04
Revises: d57654942ea4
Create Date: 2025-09-04 11:43:51.953759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b10d60b41d04'
down_revision = 'd57654942ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('origin_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('destination_name', sa.String(length=120), nullable=False))
        batch_op.drop_constraint('parcels_destination_depot_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('parcels_origin_depot_id_fkey', type_='foreignkey')
        batch_op.drop_column('origin_depot_id')
        batch_op.drop_column('destination_depot_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destination_depot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('origin_depot_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('parcels_origin_depot_id_fkey', 'depots', ['origin_depot_id'], ['id'])
        batch_op.create_foreign_key('parcels_destination_depot_id_fkey', 'depots', ['destination_depot_id'], ['id'])
        batch_op.drop_column('destination_name')
        batch_op.drop_column('origin_name')

    # ### end Alembic commands ###
