"""add settings table for hold duration

Revision ID: c0b5e5d303da
Revises: 3a8d9fbb7b33
Create Date: 2025-09-03 16:45:54.421824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b5e5d303da'
down_revision = '3a8d9fbb7b33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hold_expires_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_column('hold_expires_at')

    op.drop_table('settings')
    # ### end Alembic commands ###
