"""Add parcel photo_filename

Revision ID: d57654942ea4
Revises: c0b5e5d303da
Create Date: 2025-09-04 11:30:18.582434

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd57654942ea4'
down_revision = 'c0b5e5d303da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parcel_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('settings')
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ref_code', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('sender_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('sender_phone', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('receiver_name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('receiver_phone', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('origin_depot_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('destination_depot_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=255), nullable=True))
        batch_op.alter_column('weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.drop_constraint('parcels_tracking_number_key', type_='unique')
        batch_op.create_unique_constraint(None, ['ref_code'])
        batch_op.drop_constraint('parcels_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('parcels_trip_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'depots', ['destination_depot_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['created_by'], ['id'])
        batch_op.create_foreign_key(None, 'depots', ['origin_depot_id'], ['id'])
        batch_op.drop_column('trip_id')
        batch_op.drop_column('tracking_number')
        batch_op.drop_column('description')
        batch_op.drop_column('recipient_name')
        batch_op.drop_column('height_cm')
        batch_op.drop_column('recipient_phone')
        batch_op.drop_column('fare')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('width_cm')
        batch_op.drop_column('recipient_id_number')
        batch_op.drop_column('length_cm')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('parcels', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('length_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recipient_id_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('width_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fare', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recipient_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('recipient_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tracking_number', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('trip_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('parcels_trip_id_fkey', 'trips', ['trip_id'], ['id'])
        batch_op.create_foreign_key('parcels_sender_id_fkey', 'user', ['sender_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('parcels_tracking_number_key', ['tracking_number'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('weight_kg',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('created_by')
        batch_op.drop_column('price')
        batch_op.drop_column('destination_depot_id')
        batch_op.drop_column('origin_depot_id')
        batch_op.drop_column('receiver_phone')
        batch_op.drop_column('receiver_name')
        batch_op.drop_column('sender_phone')
        batch_op.drop_column('sender_name')
        batch_op.drop_column('ref_code')

    op.create_table('settings',
    sa.Column('key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('key', name='settings_pkey')
    )
    op.drop_table('parcel_events')
    # ### end Alembic commands ###
